# Generated by Django 5.2.7 on 2025-12-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_availability_day_of_week_postcomment_postlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="public_id",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True, unique=True
            ),
        ),
    ]
