# Generated by Django 5.2.7 on 2025-12-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calendly_url",
            field=models.URLField(
                blank=True,
                help_text="Mentor's Calendly scheduling link (e.g. https://calendly.com/yourname/30min)",
                null=True,
            ),
        ),
    ]
