# Generated by Django 5.2.7 on 2025-12-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_seen_welcome",
            field=models.BooleanField(default=False),
        ),
    ]
