# Generated by Django 5.2.7 on 2025-12-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_profile_calendly_url"),
        ("core", "0012_skill"),
    ]

    operations = []
